export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_TOTAL_ITEMS = "UPDATE_TOTAL_ITEMS";
export const UPDATE_TOTAL_AMOUNT = "UPDATE_TOTAL_AMOUNT";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE";
