export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_ERROR_RESET = "LOGIN_ERROR_RESET";
export const UPDATE_USER_CART = "UPDATE_USER_CART";
