export const GET_CUSTOMER_DATA_REQUEST = "GET_CUSTOMER_DATA_REQUEST";
export const GET_CUSTOMER_DATA_SUCCESS = "GET_CUSTOMER_DATA_SUCCESS";
export const GET_CUSTOMER_DATA_FAILURE = "GET_CUSTOMER_DATA_FAILURE";

export const UPDATE_LOGGED_USER_CART = "UPDATE_LOGGED_USER_CART";
