export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const FETCH_VIEW_PRODUCT_REQUEST = "FETCH_VIEW_PRODUCT_REQUEST";
export const FETCH_VIEW_PRODUCT_SUCCESS = "FETCH_VIEW_PRODUCT_SUCCESS";
export const FETCH_VIEW_PRODUCT_FAILURE = "FETCH_VIEW_PRODUCT_FAILURE";

export const SET_PAGE = "SET_PAGE";
